FROM python:3.10-slim

# 3. 设置工作目录
WORKDIR /app

# 4. 复制文件
COPY requirements.txt /app/

COPY third_parties/ /app/third_parties/

# 4. 安装 Python 依赖
# ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
# RUN pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
# RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple



# thundersvm
# cmake -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 ..
# cd ../python
# python setup.py install
# sudo apt-get install libnuma-dev

# 安装 flash-attn


COPY ./code/ /app/code/
# COPY ./model/ /app/model/
COPY ./init.sh /app/init.sh
COPY ./train.sh /app/train.sh
COPY ./test.sh /app/test.sh
COPY ./readme.pdf /app/readme.pdf

EXPOSE 8888
ENV JUPYTER_WORKSPACE_NAME=app
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser", "--port=8888"]
# CMD ["ipython"]

